### model
model_name_or_path: microsoft/Phi-3.5-vision-instruct
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 256
lora_alpha: 512
lora_dropout: 0.05
lora_target: qkv_proj,o_proj,gate_up_proj,down_proj,q_proj,k_proj,v_proj,out_proj,fc1,fc2

### dataset
dataset_dir: ./data
dataset: uavon_phi35_sft_depth_grid_collision_filtered_smoke
template: phi3v
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: ./outputs/phi35_uavon_lora_r256_depth_grid_collision_filtered_smoke_20260719_001301
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
max_steps: 2
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
gradient_checkpointing: false
disable_gradient_checkpointing: true
ddp_timeout: 180000000
ddp_find_unused_parameters: false
deepspeed: configs/ds_zero2.json
